# Use official PHP image
FROM php:8.2-cli

# Set working directory
WORKDIR /app

# Copy all project files
COPY . .

# Expose the port Render uses
EXPOSE 10000

# Start PHP server pointing to your root or public folder
CMD ["php", "-S", "0.0.0.0:10000", "-t", "ecom"]
